from tkinter import *

window = Tk()
window.geometry("400x500")
window.title("Calculator")
window.configure(bg="LIGHT GREY")
label = Label(window, text="Helo", width=400, height=3, justify=RIGHT, fg="BLACK", bg="WHITE")
label.pack()
btn7 = Button(window, text="7")
btn8 = Button(window, text="8")
btn9 = Button(window, text="9")
btn4 = Button(window, text="4")
btn5 = Button(window, text="5")
btn6 = Button(window, text="6")
btn1 = Button(window, text="1")
btn2 = Button(window, text="2")
btn3 = Button(window, text="3")
btnc = Button(window, text="AC")

btn7.pack()
btn8.pack()
btn9.pack()
btn7.place(bordermode=OUTSIDE, height=40, width=85, x=10, y=60)
btn8.place(bordermode=OUTSIDE, height=40, width=85, x=105, y=60)
btn9.place(bordermode=OUTSIDE, height=40, width=85, x=200, y=60)
btnc.place(bordermode=OUTSIDE, height=40, width=85, x=295, y=60)
window.mainloop()
