from tkinter import *

#Window
window = Tk()
window.geometry("400x500")
window.title("Calculator")
window.configure(bg="LIGHT GREY")
#Label
label = Label(window, text="Helo", width=400, height=3, fg="BLACK", bg="WHITE")
label.pack()
#Buttons
btnbo = Button(window, text="(")
btnbc = Button(window, text=")")
btnper = Button(window, text="%")
btnc = Button(window, text="AC")
btndiv = Button(window, text="/")
btnmul = Button(window, text="X")
btnsub = Button(window, text="-")
btnadd = Button(window, text="+")
btn0 = Button(window, text="0")
btndot = Button(window, text=".")
btneql = Button(window, text="=")
btn7 = Button(window, text="7")
btn8 = Button(window, text="8")
btn9 = Button(window, text="9")
btn4 = Button(window, text="4")
btn5 = Button(window, text="5")
btn6 = Button(window, text="6")
btn1 = Button(window, text="1")
btn2 = Button(window, text="2")
btn3 = Button(window, text="3")
#Button Style
btn1.pack()
btn2.pack()
btn3.pack()
btn4.pack()
btn5.pack()
btn6.pack()
btn7.pack()
btn8.pack()
btn9.pack()
btn0.pack()
btndot.pack()
btndiv.pack()
btneql.pack()
btnper.pack()
btnbo.pack()
btnbc.pack()
btnc.pack()
btnadd.pack()
btnsub.pack()
btnmul.pack()

btnbo.place(bordermode=OUTSIDE, height=40, width=85, x=10, y=60)
btnbc.place(bordermode=OUTSIDE, height=40, width=85, x=105, y=60)
btnper.place(bordermode=OUTSIDE, height=40, width=85, x=200, y=60)
btnc.place(bordermode=OUTSIDE, height=40, width=85, x=295, y=60)

btn7.place(bordermode=OUTSIDE, height=40, width=85, x=10, y=110)
btn8.place(bordermode=OUTSIDE, height=40, width=85, x=105, y=110)
btn9.place(bordermode=OUTSIDE, height=40, width=85, x=200, y=110)
btndiv.place(bordermode=OUTSIDE, height=40, width=85, x=295, y=110)

btn4.place(bordermode=OUTSIDE, height=40, width=85, x=10, y=160)
btn5.place(bordermode=OUTSIDE, height=40, width=85, x=105, y=160)
btn6.place(bordermode=OUTSIDE, height=40, width=85, x=200, y=160)
btnmul.place(bordermode=OUTSIDE, height=40, width=85, x=295, y=160)

btn1.place(bordermode=OUTSIDE, height=40, width=85, x=10, y=210)
btn2.place(bordermode=OUTSIDE, height=40, width=85, x=105, y=210)
btn3.place(bordermode=OUTSIDE, height=40, width=85, x=200, y=210)
btnsub.place(bordermode=OUTSIDE, height=40, width=85, x=295, y=210)

btndot.place(bordermode=OUTSIDE, height=40, width=85, x=10, y=260)
btn0.place(bordermode=OUTSIDE, height=40, width=85, x=105, y=260)
btneql.place(bordermode=OUTSIDE, height=40, width=85, x=200, y=260)
btnadd.place(bordermode=OUTSIDE, height=40, width=85, x=295, y=260)

window.mainloop()
